server:
  port: 8181


ypfp:
  customer-name: yantriksbootcamp

streamer:
  inventory-update-topic: custom-inventory-update-feed
  inventory-target-topic: inventory-update-feed
kafka:
  consumer:
    key.deserializer: com.reactivekafka.reactivekafkademo.deserialization.JacksonDeserializer
    value.deserializer: om.reactivekafka.reactivekafkademo.deserialization.JacksonDeserializer
    spring.json.trusted.packages: "*"
    spring.json.use.type.headers: false
    spring.json.key.default.type: com.bootcamp.dto.InventoryUpdateKey


    bootstrap.servers: localhost:9092
    group.id: custom-12
    auto.offset.reset: earliest
    enabled: true
    dlq-publish.enabled: true

    retry:
      limit: 1
      backoff:
        max: 15s
        initial: 10s
    commit.interval: 5s
  producer:
    key.serializer: com.yantriks.academy.kafka.serialization.JacksonSerializer
    value.serializer: com.yantriks.academy.kafka.serialization.JacksonSerializer
    bootstrap.servers: localhost:9092
    max.in.flight.requests.per.connection: 100
    acks: all
    enabled: true

